exports.languages_old = [
    {
        "locale_name": "ab_AB",
        "language_code": "ab_AB",
        "title": "Аҧсуа (ab)",
        "subject": "abkhazian (ab)",
        "language_name": "Abkhazian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "aa_AA",
        "language_code": "aa_AA",
        "title": "afaraf (aa)",
        "subject": "afaraf (aa)",
        "language_name": "Afar",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "af_AF",
        "language_code": "af_AF",
        "title": "afrikaans (af)",
        "subject": "afrikaans (af)",
        "language_name": "Afrikaans",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ak_AK",
        "language_code": "ak_AK",
        "title": "akan (ak)",
        "subject": "akan (ak)",
        "language_name": "Akan",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "sq_SQ",
        "language_code": "sq_SQ",
        "title": "Shqip (sq)",
        "subject": "shqip (sq)",
        "language_name": "Albanian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "am_AM",
        "language_code": "am_AM",
        "title": "amharic (am)",
        "subject": "amharic (am)",
        "language_name": "Amharic",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ar_AR",
        "language_code": "ar_AR",
        "title": "‫العربية ‪(ar)",
        "subject": "arabic (ar)",
        "language_name": "Arabic",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "an_AN",
        "language_code": "an_AN",
        "title": "aragonés (an)",
        "subject": "aragones (an)",
        "language_name": "Aragonese",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "hy_HY",
        "language_code": "hy_HY",
        "title": "Հայերեն (hy)",
        "subject": "armenian (hy)",
        "language_name": "Armenian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "as_AS",
        "language_code": "as_AS",
        "title": "Ôxômiya (as)",
        "subject": "oxomiya (as)",
        "language_name": "Assamese",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "av_AV",
        "language_code": "av_AV",
        "title": "авар мацӀ (av)",
        "subject": "avaric (av)",
        "language_name": "Avaric",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ae_AE",
        "language_code": "ae_AE",
        "title": "avestan (ae)",
        "subject": "avesta (ae)",
        "language_name": "Avesta",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ay_AY",
        "language_code": "ay_AY",
        "title": "aymar aru (ay)",
        "subject": "aymar aru (ay)",
        "language_name": "Aymara",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "aAZ",
        "language_code": "aAZ",
        "title": "Azərbaycan dili (az)",
        "subject": "azerbaycan dili (az)",
        "language_name": "Azerbaijani",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "bm_BM",
        "language_code": "bm_BM",
        "title": "bamanankan (bm)",
        "subject": "bamanankan (bm)",
        "language_name": "Bambara",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ba_BA",
        "language_code": "ba_BA",
        "title": "башҡорт теле (ba)",
        "subject": "bashkir (ba)",
        "language_name": "Bashkir",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "eu_EU",
        "language_code": "eu_EU",
        "title": "euskara (eu)",
        "subject": "euskara (eu)",
        "language_name": "Basque",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "be_BE",
        "language_code": "be_BE",
        "title": "Беларуская (be)",
        "subject": "belarusian (be)",
        "language_name": "Belarusian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "bn_BN",
        "language_code": "bn_BN",
        "title": "বাংলা (bn)",
        "subject": "bengali (bn)",
        "language_name": "Bengali",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "bh_BH",
        "language_code": "bh_BH",
        "title": "भोजपुरी (bh)",
        "subject": "bihari (bh)",
        "language_name": "Bihari",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "bi_BI",
        "language_code": "bi_BI",
        "title": "bislama (bi)",
        "subject": "bislama (bi)",
        "language_name": "Bislama",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "bs_BS",
        "language_code": "bs_BS",
        "title": "bosanski jezik (bs)",
        "subject": "bosanski jezik (bs)",
        "language_name": "Bosnian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "br_BR",
        "language_code": "br_BR",
        "title": "brezhoneg (br)",
        "subject": "brezhoneg (br)",
        "language_name": "Breton",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "bg_BG",
        "language_code": "bg_BG",
        "title": "български (bg)",
        "subject": "balgarski (bg)",
        "language_name": "Bulgarian",
        "country_name": "Republic of Bulgaria",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "my_MY",
        "language_code": "my_MY",
        "title": "burmese (my)",
        "subject": "burmese (my)",
        "language_name": "Burmese",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ca_ES",
        "language_code": "ca_ES",
        "title": "català (ca)",
        "subject": "catala (ca)",
        "language_name": "Catalan",
        "country_name": "Spain",
        "encoding_name": "UTF-8",
        "type": "EU non official language",
        "type_value": "2"
    },
    {
        "locale_name": "ch_CH",
        "language_code": "ch_CH",
        "title": "chamoru (ch)",
        "subject": "chamoru (ch)",
        "language_name": "Chamorro",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ce_CE",
        "language_code": "ce_CE",
        "title": "нохчийн мотт (ce)",
        "subject": "chechen (ce)",
        "language_name": "Chechen",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ny_NY",
        "language_code": "ny_NY",
        "title": "chiCheŵa (ny)",
        "subject": "chichewa (ny)",
        "language_name": "Chichewa",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "zh_ZH",
        "language_code": "zh_ZH",
        "title": "中文 (zh)",
        "subject": "chinese (zh)",
        "language_name": "Chinese simplified",
        "country_name": "China",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "zt_ZT",
        "language_code": "zt_ZT",
        "title": "漢語 (zt)",
        "subject": "chinese (zt)",
        "language_name": "Chinese traditional",
        "country_name": "Taiwan",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "cu_CU",
        "language_code": "cu_CU",
        "title": "ѩзыкъ словѣньскъ (cu)",
        "subject": "church slavic (cu)",
        "language_name": "Church Slavic",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "cv_CV",
        "language_code": "cv_CV",
        "title": "чӑваш чӗлхи (cv)",
        "subject": "chuvash (cv)",
        "language_name": "Chuvash",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "kw_KW",
        "language_code": "kw_KW",
        "title": "Kernewek (kw)",
        "subject": "kernewek (kw)",
        "language_name": "Cornish",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "co_CO",
        "language_code": "co_CO",
        "title": "corsu (co)",
        "subject": "corsu (co)",
        "language_name": "Corsican",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "cr_CR",
        "language_code": "cr_CR",
        "title": "cree (cr)",
        "subject": "cree (cr)",
        "language_name": "Cree",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "hr_HR",
        "language_code": "hr_HR",
        "title": "hrvatski (hr)",
        "subject": "hrvatski (hr)",
        "language_name": "Croatian",
        "country_name": "Republic of Croatia",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "cs_CZ",
        "language_code": "cs_CZ",
        "title": "čeština (cs)",
        "subject": "cestina (cs)",
        "language_name": "Czech",
        "country_name": "Czech Republic",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "da_DK",
        "language_code": "da_DK",
        "title": "dansk (da)",
        "subject": "dansk (da)",
        "language_name": "Danish",
        "country_name": "Denmark",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "dv_DV",
        "language_code": "dv_DV",
        "title": "‫ދިވެހ ‪(dv)",
        "subject": "divehi (dv)",
        "language_name": "Divehi",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "nl_NL",
        "language_code": "nl_NL",
        "title": "Nederlands (nl)",
        "subject": "nederlands (nl)",
        "language_name": "Dutch",
        "country_name": "Netherlands - Belgium",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "dDZ",
        "language_code": "dDZ",
        "title": "རྫོང་ཁ (dz)",
        "subject": "dzongkha (dz)",
        "language_name": "Dzongkha",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "en_UK",
        "language_code": "en_UK",
        "title": "English (en)",
        "subject": "english (en)",
        "language_name": "English",
        "country_name": "United Kingdom",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "16"
    },
    {
        "locale_name": "eo_EO",
        "language_code": "eo_EO",
        "title": "esperanto (eo)",
        "subject": "esperanto (eo)",
        "language_name": "Esperanto",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "et_EE",
        "language_code": "et_EE",
        "title": "eesti keel (et)",
        "subject": "eesti keel (et)",
        "language_name": "Estonian",
        "country_name": "Estonia",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "ee_EE",
        "language_code": "ee_EE",
        "title": "Ɛʋɛgbɛ (ee)",
        "subject": "ewe (ee)",
        "language_name": "Ewe",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "fo_FO",
        "language_code": "fo_FO",
        "title": "Føroyskt (fo)",
        "subject": "faroese (fo)",
        "language_name": "Faroese",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "fj_FJ",
        "language_code": "fj_FJ",
        "title": "vosa Vakaviti (fj)",
        "subject": "vosa Vakaviti (fj)",
        "language_name": "Fijian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "fi_FI",
        "language_code": "fi_FI",
        "title": "suomi (fi)",
        "subject": "suomi (fi)",
        "language_name": "Finnish",
        "country_name": "Finland",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "fr_FR",
        "language_code": "fr_FR",
        "title": "français (fr)",
        "subject": "francais (fr)",
        "language_name": "French",
        "country_name": "France - Belgique",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "16"
    },
    {
        "locale_name": "ff_FF",
        "language_code": "ff_FF",
        "title": "fulfulde (ff)",
        "subject": "fulfulde (ff)",
        "language_name": "Fulah",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "gl_GL",
        "language_code": "gl_GL",
        "title": "Galego (gl)",
        "subject": "galego (gl)",
        "language_name": "Galician",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "lg_LG",
        "language_code": "lg_LG",
        "title": "Luganda (lg)",
        "subject": "luganda (lg)",
        "language_name": "Ganda",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ka_KA",
        "language_code": "ka_KA",
        "title": "ქართული (ka)",
        "subject": "georgian (ka)",
        "language_name": "Georgian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "de_DE",
        "language_code": "de_DE",
        "title": "Deutsch (de)",
        "subject": "deutsch (de)",
        "language_name": "German",
        "country_name": "Germany",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "16"
    },
    {
        "locale_name": "el_GR",
        "language_code": "el_GR",
        "title": "ελληνικά (el)",
        "subject": "ellinika (el)",
        "language_name": "Greek",
        "country_name": "Greece",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "gn_GN",
        "language_code": "gn_GN",
        "title": "Avañe'ẽ (gn)",
        "subject": "guaraní (gn)",
        "language_name": "Guaraní",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "gu_GU",
        "language_code": "gu_GU",
        "title": "ગુજરાતી (gu)",
        "subject": "gujarati (gu)",
        "language_name": "Gujarati",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ht_HT",
        "language_code": "ht_HT",
        "title": "Kreyòl ayisyen (ht)",
        "subject": "kreyol ayisyen (ht)",
        "language_name": "Haitian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ha_HA",
        "language_code": "ha_HA",
        "title": "‫هَوُسَ ‪(ha)",
        "subject": "hausa (ha)",
        "language_name": "Hausa",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "he_HE",
        "language_code": "he_HE",
        "title": "‫עברית ‪(he)",
        "subject": "hebrew (he)",
        "language_name": "Hebrew",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "hHZ",
        "language_code": "hHZ",
        "title": "Otjiherero (hz)",
        "subject": "otjiherero (hz)",
        "language_name": "Herero",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "hi_HI",
        "language_code": "hi_HI",
        "title": "हिन्दी (hi)",
        "subject": "hindi (hi)",
        "language_name": "Hindi",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ho_HO",
        "language_code": "ho_HO",
        "title": "hiri motu (ho)",
        "subject": "hiri motu (ho)",
        "language_name": "Hiri Motu",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "hu_HU",
        "language_code": "hu_HU",
        "title": "magyar (hu)",
        "subject": "magyar (hu)",
        "language_name": "Hungarian",
        "country_name": "Hungary",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "is_IS",
        "language_code": "is_IS",
        "title": "islensk (is)",
        "subject": "islensk (is)",
        "language_name": "Icelandic",
        "country_name": "Iceland",
        "encoding_name": "UTF-8",
        "type": "EU non official language",
        "type_value": "1"
    },
    {
        "locale_name": "io_IO",
        "language_code": "io_IO",
        "title": "ido (io)",
        "subject": "ido (io)",
        "language_name": "Ido",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ig_IG",
        "language_code": "ig_IG",
        "title": "igbo (ig)",
        "subject": "igbo (ig)",
        "language_name": "Igbo",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "id_ID",
        "language_code": "id_ID",
        "title": "Bahasa Indonesia (id)",
        "subject": "bahasa Indonesia (id)",
        "language_name": "Indonesian",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ia_IA",
        "language_code": "ia_IA",
        "title": "interlingua (ia)",
        "subject": "interlingua (International Auxiliary Language Association) (ia)",
        "language_name": "Interlingua",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ie_IE",
        "language_code": "ie_IE",
        "title": "interlingue (ie)",
        "subject": "interlingue (ie)",
        "language_name": "Interlingue",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "iu_IU",
        "language_code": "iu_IU",
        "title": "inuktitut (iu)",
        "subject": "inuktitut (iu)",
        "language_name": "Inuktitut",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ik_IK",
        "language_code": "ik_IK",
        "title": "Iñupiaq (ik)",
        "subject": "inupiaq (ik)",
        "language_name": "Inupiaq",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ga_GA",
        "language_code": "ga_GA",
        "title": "Gaeilge (ga)",
        "subject": "gaeilge (ga)",
        "language_name": "Irish",
        "country_name": "Ireland",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "it_IT",
        "language_code": "it_IT",
        "title": "italiano (it)",
        "subject": "italiano (it)",
        "language_name": "Italian",
        "country_name": "Italy",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "ja_JP",
        "language_code": "ja_JP",
        "title": "日本語 (ja)",
        "subject": "japanese (ja)",
        "language_name": "Japanese",
        "country_name": "Japan",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "jv_JV",
        "language_code": "jv_JV",
        "title": "basa Jawa (jv)",
        "subject": "basa Jawa (jv)",
        "language_name": "Javanese",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "kl_KL",
        "language_code": "kl_KL",
        "title": "kalaallisut (kl)",
        "subject": "kalaallisut (kl)",
        "language_name": "Kalaallisut",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "kn_KN",
        "language_code": "kn_KN",
        "title": "ಕನ್ನಡ (kn)",
        "subject": "kannada (kn)",
        "language_name": "Kannada",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "kr_KR",
        "language_code": "kr_KR",
        "title": "kanuri (kr)",
        "subject": "kanuri (kr)",
        "language_name": "Kanuri",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ks_KS",
        "language_code": "ks_KS",
        "title": "कश्मीरी (ks)",
        "subject": "kashmiri (ks)",
        "language_name": "Kashmiri",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "kk_KK",
        "language_code": "kk_KK",
        "title": "Қазақ тілі (kk)",
        "subject": "kazakh (kk)",
        "language_name": "Kazakh",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "km_KM",
        "language_code": "km_KM",
        "title": "ភាសាខ្មែរ (km)",
        "subject": "khmer (km)",
        "language_name": "Khmer",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ki_KI",
        "language_code": "ki_KI",
        "title": "Gĩkũyũ (ki)",
        "subject": "gikuyu (ki)",
        "language_name": "Kikuyu",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "rw_RW",
        "language_code": "rw_RW",
        "title": "Ikinyarwanda (rw)",
        "subject": "lkinyarwanda (rw)",
        "language_name": "Kinyarwanda",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ky_KY",
        "language_code": "ky_KY",
        "title": "кыргыз тили (ky)",
        "subject": "kirghiz (ky)",
        "language_name": "Kirghiz",
        "country_name": "Kyrgyzstan",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "rn_RN",
        "language_code": "rn_RN",
        "title": "kiRundi (rn)",
        "subject": "kirundi (rn)",
        "language_name": "Kirundi",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "kv_KV",
        "language_code": "kv_KV",
        "title": "коми кыв (kv)",
        "subject": "komi (kv)",
        "language_name": "Komi",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "kg_KG",
        "language_code": "kg_KG",
        "title": "KiKongo (kg)",
        "subject": "kikongo (kg)",
        "language_name": "Kongo",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ko_KO",
        "language_code": "ko_KO",
        "title": "한국어 (韓國語) (ko)",
        "subject": "korean (ko)",
        "language_name": "Korean",
        "country_name": "South Korea",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ku_KU",
        "language_code": "ku_KU",
        "title": "Kurdî (ku)",
        "subject": "kurdi (ku)",
        "language_name": "Kurdish",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "kj_KJ",
        "language_code": "kj_KJ",
        "title": "Kuanyama (kj)",
        "subject": "kuanyama (kj)",
        "language_name": "Kwanyama",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "lo_LO",
        "language_code": "lo_LO",
        "title": "ພາສາລາວ (lo)",
        "subject": "lao (lo)",
        "language_name": "Lao",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "la_LA",
        "language_code": "la_LA",
        "title": "latine (la)",
        "subject": "latine (la)",
        "language_name": "Latin",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "lv_LV",
        "language_code": "lv_LV",
        "title": "latviešu valoda (lv)",
        "subject": "latviesu valoda (lv)",
        "language_name": "Lettish",
        "country_name": "Latvia",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "li_LI",
        "language_code": "li_LI",
        "title": "Limburgs (li)",
        "subject": "limburgs (li)",
        "language_name": "Limburgish",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "ln_LN",
        "language_code": "ln_LN",
        "title": "Lingála (ln)",
        "subject": "lingala (ln)",
        "language_name": "Lingala",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "lt_LT",
        "language_code": "lt_LT",
        "title": "lietuvių kalba (lt)",
        "subject": "lietuviu kalba (lt)",
        "language_name": "Lithuanian",
        "country_name": "Lithuania",
        "encoding_name": "UTF-8",
        "type": "EU official language",
        "type_value": "8"
    },
    {
        "locale_name": "lu_LU",
        "language_code": "lu_LU",
        "title": "luba-katanga (lu)",
        "subject": "luba-katanga (lu)",
        "language_name": "Luba-Katanga",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "lb_LB",
        "language_code": "lb_LB",
        "title": "Lëtzebuergesch (lb)",
        "subject": "Letzebuergesch (lb)",
        "language_name": "Luxembourgish",
        "country_name": "",
        "encoding_name": "UTF-8",
        "type": "Non EU language",
        "type_value": "4"
    },
    {
        "locale_name": "mk_MK",
        "language_code": "mk_MK",
        "title": "makedonski (mk)",
        "subject": "makedonski (mk)",
        "language_name": "Macedonian",
        "country_name": "Macedonia",
        "encoding_name": "UTF-8",
        "type": "EU non official language",
        "type_value": "1"
    },
{
    "locale_name": "mg_MG",
    "language_code": "mg_MG",
    "title": "Malagasy fiteny (mg)",
    "subject": "malagasy fiteny (mg)",
    "language_name": "Malagasy",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ms_MS",
    "language_code": "ms_MS",
    "title": "بهاس ملاي (ms)",
    "subject": "bahasa melayu (ms)",
    "language_name": "Malay",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ml_ML",
    "language_code": "ml_ML",
    "title": "Malayalam (ml)",
    "subject": "malayalam (ml)",
    "language_name": "Malayalam",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "mt_MT",
    "language_code": "mt_MT",
    "title": "Malti (mt)",
    "subject": "malti (mt)",
    "language_name": "Maltese",
    "country_name": "Malta",
    "encoding_name": "UTF-8",
    "type": "EU official language",
    "type_value": "8"
},
{
    "locale_name": "gv_GV",
    "language_code": "gv_GV",
    "title": "Ghaelg (gv)",
    "subject": "ghaelg (gv)",
    "language_name": "Manx",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "mi_MI",
    "language_code": "mi_MI",
    "title": "te reo Māori (mi)",
    "subject": "te reo maori (mi)",
    "language_name": "Māori",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "mr_MR",
    "language_code": "mr_MR",
    "title": "मराठी (mr)",
    "subject": "marathi (mr)",
    "language_name": "Marathi",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "mh_MH",
    "language_code": "mh_MH",
    "title": "Kajin M̧ajeļ (mh)",
    "subject": "kajin majel (mh)",
    "language_name": "Marshallese",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "mo_MO",
    "language_code": "mo_MO",
    "title": "Moldovenească (mo)",
    "subject": "moldavian (mo)",
    "language_name": "Moldavian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "mn_MN",
    "language_code": "mn_MN",
    "title": "Монгол (mn)",
    "subject": "mongolian (mn)",
    "language_name": "Mongolian",
    "country_name": "Mongolia",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "na_NA",
    "language_code": "na_NA",
    "title": "Ekakairũ Naoero (na)",
    "subject": "ekakairu Naoero (na)",
    "language_name": "Nauru",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "nv_NV",
    "language_code": "nv_NV",
    "title": "Diné bizaad (nv)",
    "subject": "Dine bizaad (nv)",
    "language_name": "Navajo",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ng_NG",
    "language_code": "ng_NG",
    "title": "Owambo (ng)",
    "subject": "owambo (ng)",
    "language_name": "Ndonga",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ne_NE",
    "language_code": "ne_NE",
    "title": "नेपाली (ne)",
    "subject": "nepali (ne)",
    "language_name": "Nepali",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ZZ",
    "language_code": "ZZ",
    "title": "No language (zz)",
    "subject": "zz (zz)",
    "language_name": "No language",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "nd_ND",
    "language_code": "nd_ND",
    "title": "isiNdebele (nd)",
    "subject": " isindebele (nd)",
    "language_name": "North Ndebele",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "se_SE",
    "language_code": "se_SE",
    "title": "Davvisámegiella (se)",
    "subject": "davvisamegiella (se)",
    "language_name": "Northern Sami",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "no_NO",
    "language_code": "no_NO",
    "title": "norsk (no)",
    "subject": "norsk (no)",
    "language_name": "Norwegian",
    "country_name": "Norway",
    "encoding_name": "UTF-8",
    "type": "EU non official language",
    "type_value": "1"
},
{
    "locale_name": "nb_NO",
    "language_code": "nb_NO",
    "title": "Norsk bokmål (nb)",
    "subject": "norsk bokmal (nb)",
    "language_name": "Norwegian Bokmål",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "nn_NN",
    "language_code": "nn_NN",
    "title": "Norsk nynorsk (nn)",
    "subject": "norsk nynorsk (nn)",
    "language_name": "Norwegian Nynorsk",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "oc_OC",
    "language_code": "oc_OC",
    "title": "occitan (oc)",
    "subject": "occitan (oc)",
    "language_name": "Occitan",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "oj_OJ",
    "language_code": "oj_OJ",
    "title": "ojibwa (oj)",
    "subject": "ojibwa (oj)",
    "language_name": "Ojibwa",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "or_OR",
    "language_code": "or_OR",
    "title": "Oriya (or)",
    "subject": "oriya (or)",
    "language_name": "Oriya",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "om_OM",
    "language_code": "om_OM",
    "title": "Afaan Oromoo (om)",
    "subject": "afaan_oromoo (om)",
    "language_name": "Oromo",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "os_OS",
    "language_code": "os_OS",
    "title": "Ирон æвзаг (os)",
    "subject": "ossetian (os)",
    "language_name": "Ossetian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "pi_PI",
    "language_code": "pi_PI",
    "title": "पाऴि (pi)",
    "subject": "pali (pi)",
    "language_name": "Pāli",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "pa_PA",
    "language_code": "pa_PA",
    "title": "ਪੰਜਾਬੀ (pa)",
    "subject": "panjabi (pa)",
    "language_name": "Panjabi",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ps_PS",
    "language_code": "ps_PS",
    "title": "‫پښتو ‪(ps)",
    "subject": "pashto (ps)",
    "language_name": "Pashto",
    "country_name": "Afghanistan",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "fa_FA",
    "language_code": "fa_FA",
    "title": "‫فارسی ‪(fa)",
    "subject": "persian (fa)",
    "language_name": "Persian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "pl_PL",
    "language_code": "pl_PL",
    "title": "polski (pl)",
    "subject": "polski (pl)",
    "language_name": "Polish",
    "country_name": "Poland",
    "encoding_name": "UTF-8",
    "type": "EU official language",
    "type_value": "8"
},
{
    "locale_name": "pt_PT",
    "language_code": "pt_PT",
    "title": "português (pt)",
    "subject": "portugues (pt)",
    "language_name": "Portuguese",
    "country_name": "Portugal",
    "encoding_name": "UTF-8",
    "type": "EU official language",
    "type_value": "8"
},
{
    "locale_name": "qu_QU",
    "language_code": "qu_QU",
    "title": "Kichwa (qu)",
    "subject": "kichwa (qu)",
    "language_name": "Quechua",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "rm_RM",
    "language_code": "rm_RM",
    "title": "rumantsch grischun (rm)",
    "subject": "rumantsch grischun (rm)",
    "language_name": "Raeto-Romance",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ro_RO",
    "language_code": "ro_RO",
    "title": "română (ro)",
    "subject": "romana (ro)",
    "language_name": "Romanian",
    "country_name": "Romania",
    "encoding_name": "UTF-8",
    "type": "EU official language",
    "type_value": "8"
},
{
    "locale_name": "ru_RU",
    "language_code": "ru_RU",
    "title": "русский язык (ru)",
    "subject": "russian (ru)",
    "language_name": "Russian",
    "country_name": "RUSSIAN FEDERATION",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sm_SM",
    "language_code": "sm_SM",
    "title": "gagana fa'a Samoa (sm)",
    "subject": "gagana fa a Samoa (sm)",
    "language_name": "Samoan",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sg_SG",
    "language_code": "sg_SG",
    "title": "yângâ tî sängö (sg)",
    "subject": "yanga ti sango (sg)",
    "language_name": "Sango",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sa_SA",
    "language_code": "sa_SA",
    "title": "संस्कृतम (sa)",
    "subject": "sanskrit (sa)",
    "language_name": "Sanskrit",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sc_SC",
    "language_code": "sc_SC",
    "title": "sardu (sc)",
    "subject": "sardu (sc)",
    "language_name": "Sardinian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "gd_GD",
    "language_code": "gd_GD",
    "title": "Gàidhlig (gd)",
    "subject": "gaidhlig (gd)",
    "language_name": "Scottish Gaelic",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sr_SR",
    "language_code": "sr_SR",
    "title": "Srpski (sr)",
    "subject": "serbian (sr)",
    "language_name": "Serbian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sh_SH",
    "language_code": "sh_SH",
    "title": "Српскохрватски (sh)",
    "subject": "serbo-croatian (sh)",
    "language_name": "Serbo-Croatian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sn_SN",
    "language_code": "sn_SN",
    "title": "chiShona (sn)",
    "subject": "chishona (sn)",
    "language_name": "Shona",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ii_II",
    "language_code": "ii_II",
    "title": "sichuan yi (ii)",
    "subject": "sichuan yi (ii)",
    "language_name": "Sichuan Yi",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sd_SD",
    "language_code": "sd_SD",
    "title": "सिन्धी (sd)",
    "subject": "sindhi (sd)",
    "language_name": "Sindhi",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "si_SI",
    "language_code": "si_SI",
    "title": "සිංහල (si)",
    "subject": "sinhalese (si)",
    "language_name": "Sinhalese",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sk_SK",
    "language_code": "sk_SK",
    "title": "slovenčina (sk)",
    "subject": "slovencina (sk)",
    "language_name": "Slovak",
    "country_name": "Slovakia",
    "encoding_name": "UTF-8",
    "type": "EU official language",
    "type_value": "8"
},
{
    "locale_name": "sl_SI",
    "language_code": "sl_SI",
    "title": "slovenščina (sl)",
    "subject": "slovenscina (sl)",
    "language_name": "Slovenian",
    "country_name": "Slovenia",
    "encoding_name": "UTF-8",
    "type": "EU official language",
    "type_value": "8"
},
{
    "locale_name": "so_SO",
    "language_code": "so_SO",
    "title": "Soomaaliga (so)",
    "subject": "soomaaliga (so)",
    "language_name": "Somali",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "st_ST",
    "language_code": "st_ST",
    "title": "Sesotho (st)",
    "subject": "sesotho (st)",
    "language_name": "Sotho",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "nr_NR",
    "language_code": "nr_NR",
    "title": "Ndébélé (nr)",
    "subject": "ndebele (nr)",
    "language_name": "South Ndebele",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "es_ES",
    "language_code": "es_ES",
    "title": "español (es)",
    "subject": "espanol (es)",
    "language_name": "Spanish",
    "country_name": "Spain",
    "encoding_name": "UTF-8",
    "type": "EU official language",
    "type_value": "8"
},
{
    "locale_name": "su_SU",
    "language_code": "su_SU",
    "title": "Basa Sunda (su)",
    "subject": "basasunda (su)",
    "language_name": "Sundanese",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sw_SW",
    "language_code": "sw_SW",
    "title": "Kiswahili (sw)",
    "subject": "kiswahili (sw)",
    "language_name": "Swahili",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ss_SS",
    "language_code": "ss_SS",
    "title": "SiSwati (ss)",
    "subject": "siswati (ss)",
    "language_name": "Swati",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "sv_SE",
    "language_code": "sv_SE",
    "title": "svenska (sv)",
    "subject": "svenska (sv)",
    "language_name": "Swedish",
    "country_name": "Sweden",
    "encoding_name": "UTF-8",
    "type": "EU official language",
    "type_value": "8"
},
{
    "locale_name": "tl_TL",
    "language_code": "tl_TL",
    "title": "tagalog (tl)",
    "subject": "tagalog (tl)",
    "language_name": "Tagalog",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ty_TY",
    "language_code": "ty_TY",
    "title": "Reo Mā`ohi (ty)",
    "subject": "reo Ma ohi (ty)",
    "language_name": "Tahitian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "tg_TG",
    "language_code": "tg_TG",
    "title": "тоҷикӣ (tg)",
    "subject": "tajik (tg)",
    "language_name": "Tajik",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ta_TA",
    "language_code": "ta_TA",
    "title": "தமிழ் (ta)",
    "subject": "tamil (ta)",
    "language_name": "Tamil",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "tt_TT",
    "language_code": "tt_TT",
    "title": "татарча (tt)",
    "subject": "tatar (tt)",
    "language_name": "Tatar",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "te_TE",
    "language_code": "te_TE",
    "title": "తెలుగు (te)",
    "subject": "telugu (te)",
    "language_name": "Telugu",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "tm_TM",
    "language_code": "tm_TM",
    "title": "Tetun (tn)",
    "subject": "tetum (tm)",
    "language_name": "Tetum",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "th_TH",
    "language_code": "th_TH",
    "title": "ไทย (th)",
    "subject": "thai (th)",
    "language_name": "Thai",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "bo_BO",
    "language_code": "bo_BO",
    "title": "བོད་ཡིག (bo)",
    "subject": "tibetan (bo)",
    "language_name": "Tibetan",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ti_TI",
    "language_code": "ti_TI",
    "title": "tigrinya (ti)",
    "subject": "tigrinya (ti)",
    "language_name": "Tigrinya",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "to_TO",
    "language_code": "to_TO",
    "title": "faka Tonga (to)",
    "subject": "faka tonga (to)",
    "language_name": "Tonga",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ts_TS",
    "language_code": "ts_TS",
    "title": "xiTsonga (ts)",
    "subject": "xitsonga (ts)",
    "language_name": "Tsonga",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "tn_TN",
    "language_code": "tn_TN",
    "title": "seTswana (tn)",
    "subject": "setswana (tn)",
    "language_name": "Tswana",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "tr_TR",
    "language_code": "tr_TR",
    "title": "Türkçe (tr)",
    "subject": "turkce (tr)",
    "language_name": "Turkish",
    "country_name": "Republic of Turkey",
    "encoding_name": "UTF-8",
    "type": "EU non official language",
    "type_value": "1"
},
{
    "locale_name": "tk_TK",
    "language_code": "tk_TK",
    "title": "Türkmen (tk)",
    "subject": "turkmen (tk)",
    "language_name": "Turkmen",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "tw_TW",
    "language_code": "tw_TW",
    "title": "twi (tw)",
    "subject": "twi (tw)",
    "language_name": "Twi",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ug_UG",
    "language_code": "ug_UG",
    "title": "yƣurqə (ug)",
    "subject": "uighur (ug)",
    "language_name": "Uighur",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "uk_UK",
    "language_code": "uk_UK",
    "title": "Українська (uk)",
    "subject": "ukrainian (uk)",
    "language_name": "Ukrainian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ur_UR",
    "language_code": "ur_UR",
    "title": "‫اردو ‪(ur)",
    "subject": "urdu (ur)",
    "language_name": "Urdu",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "uUZ",
    "language_code": "uUZ",
    "title": "O'zbek (uz)",
    "subject": "ozbek (uz)",
    "language_name": "Uzbek",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "ve_VE",
    "language_code": "ve_VE",
    "title": "tshiVenḓa (ve)",
    "subject": "tshivenda (ve)",
    "language_name": "Venda",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "vi_VI",
    "language_code": "vi_VI",
    "title": "Tiếng Việt (vi)",
    "subject": "tieng viet (vi)",
    "language_name": "Vietnamese",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "vo_VO",
    "language_code": "vo_VO",
    "title": "volapük (vo)",
    "subject": "volapuk (vo)",
    "language_name": "Volapük",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "wa_WA",
    "language_code": "wa_WA",
    "title": "walon (wa)",
    "subject": "walon (wa)",
    "language_name": "Walloon",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "cy_CY",
    "language_code": "cy_CY",
    "title": "cymraeg (cy)",
    "subject": "welsh (cy)",
    "language_name": "Welsh",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "fy_FY",
    "language_code": "fy_FY",
    "title": "Frysk (fy)",
    "subject": "frysk (fy)",
    "language_name": "Western Frisian",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "wo_WO",
    "language_code": "wo_WO",
    "title": "Wollof (wo)",
    "subject": "wollof (wo)",
    "language_name": "Wolof",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "xh_XH",
    "language_code": "xh_XH",
    "title": "isiXhosa (xh)",
    "subject": "isixhosa (xh)",
    "language_name": "Xhosa",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "yi_YI",
    "language_code": "yi_YI",
    "title": "‫ייִדיש ‪(yi)",
    "subject": "yiddish (yi)",
    "language_name": "Yiddish",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "yo_YO",
    "language_code": "yo_YO",
    "title": "Yorùbá (yo)",
    "subject": "yoruba (yo)",
    "language_name": "Yoruba",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "za_ZA",
    "language_code": "za_ZA",
    "title": "Saɯ cueŋƅ (za)",
    "subject": "zhuang (za)",
    "language_name": "Zhuang",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
},
{
    "locale_name": "zu_ZU",
    "language_code": "zu_ZU",
    "title": "isiZulu (zu)",
    "subject": "isizulu (zu)",
    "language_name": "Zulu",
    "country_name": "",
    "encoding_name": "UTF-8",
    "type": "Non EU language",
    "type_value": "4"
}
    ]

exports.languages = {
    "ab": {
        "label": "Аҧсуа (ab)",
        "order": "abkhazian (ab)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "aa": {"label": "afaraf (aa)", "order": "afaraf (aa)", "type": "Non EU language", "type_value": "4"},
    "af": {"label": "afrikaans (af)", "order": "afrikaans (af)", "type": "Non EU language", "type_value": "4"},
    "ak": {"label": "akan (ak)", "order": "akan (ak)", "type": "Non EU language", "type_value": "4"},
    "sq": {"label": "Shqip (sq)", "order": "shqip (sq)", "type": "Non EU language", "type_value": "4"},
    "am": {"label": "amharic (am)", "order": "amharic (am)", "type": "Non EU language", "type_value": "4"},
    "ar": {"label": "‫العربية ‪(ar)", "order": "arabic (ar)", "type": "Non EU language", "type_value": "4"},
    "an": {"label": "aragonés (an)", "order": "aragones (an)", "type": "Non EU language", "type_value": "4"},
    "hy": {"label": "Հայերեն (hy)", "order": "armenian (hy)", "type": "Non EU language", "type_value": "4"},
    "as": {"label": "Ôxômiya (as)", "order": "oxomiya (as)", "type": "Non EU language", "type_value": "4"},
    "av": {"label": "авар мацӀ (av)", "order": "avaric (av)", "type": "Non EU language", "type_value": "4"},
    "ae": {"label": "avestan (ae)", "order": "avesta (ae)", "type": "Non EU language", "type_value": "4"},
    "ay": {"label": "aymar aru (ay)", "order": "aymar aru (ay)", "type": "Non EU language", "type_value": "4"},
    "aA": {
        "label": "Azərbaycan dili (az)",
        "order": "azerbaycan dili (az)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "bm": {"label": "bamanankan (bm)", "order": "bamanankan (bm)", "type": "Non EU language", "type_value": "4"},
    "ba": {"label": "башҡорт теле (ba)", "order": "bashkir (ba)", "type": "Non EU language", "type_value": "4"},
    "eu": {"label": "euskara (eu)", "order": "euskara (eu)", "type": "Non EU language", "type_value": "4"},
    "be": {"label": "Беларуская (be)", "order": "belarusian (be)", "type": "Non EU language", "type_value": "4"},
    "bn": {"label": "বাংলা (bn)", "order": "bengali (bn)", "type": "Non EU language", "type_value": "4"},
    "bh": {"label": "भोजपुरी (bh)", "order": "bihari (bh)", "type": "Non EU language", "type_value": "4"},
    "bi": {"label": "bislama (bi)", "order": "bislama (bi)", "type": "Non EU language", "type_value": "4"},
    "bs": {
        "label": "bosanski jezik (bs)",
        "order": "bosanski jezik (bs)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "br": {"label": "brezhoneg (br)", "order": "brezhoneg (br)", "type": "Non EU language", "type_value": "4"},
    "bg": {"label": "български (bg)", "order": "balgarski (bg)", "type": "EU official language", "type_value": "8"},
    "my": {"label": "burmese (my)", "order": "burmese (my)", "type": "Non EU language", "type_value": "4"},
    "ca": {"label": "català (ca)", "order": "catala (ca)", "type": "EU non official language", "type_value": "2"},
    "ch": {"label": "chamoru (ch)", "order": "chamoru (ch)", "type": "Non EU language", "type_value": "4"},
    "ce": {"label": "нохчийн мотт (ce)", "order": "chechen (ce)", "type": "Non EU language", "type_value": "4"},
    "ny": {"label": "chiCheŵa (ny)", "order": "chichewa (ny)", "type": "Non EU language", "type_value": "4"},
    "zh": {"label": "中文 (zh)", "order": "chinese (zh)", "type": "Non EU language", "type_value": "4"},
    "zt": {"label": "漢語 (zt)", "order": "chinese (zt)", "type": "Non EU language", "type_value": "4"},
    "cu": {
        "label": "ѩзыкъ словѣньскъ (cu)",
        "order": "church slavic (cu)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "cv": {"label": "чӑваш чӗлхи (cv)", "order": "chuvash (cv)", "type": "Non EU language", "type_value": "4"},
    "kw": {"label": "Kernewek (kw)", "order": "kernewek (kw)", "type": "Non EU language", "type_value": "4"},
    "co": {"label": "corsu (co)", "order": "corsu (co)", "type": "Non EU language", "type_value": "4"},
    "cr": {"label": "cree (cr)", "order": "cree (cr)", "type": "Non EU language", "type_value": "4"},
    "hr": {"label": "hrvatski (hr)", "order": "hrvatski (hr)", "type": "EU official language", "type_value": "8"},
    "cs": {"label": "čeština (cs)", "order": "cestina (cs)", "type": "EU official language", "type_value": "8"},
    "da": {"label": "dansk (da)", "order": "dansk (da)", "type": "EU official language", "type_value": "8"},
    "dv": {"label": "‫ދިވެހ ‪(dv)", "order": "divehi (dv)", "type": "Non EU language", "type_value": "4"},
    "nl": {"label": "Nederlands (nl)", "order": "nederlands (nl)", "type": "EU official language", "type_value": "8"},
    "dD": {"label": "རྫོང་ཁ (dz)", "order": "dzongkha (dz)", "type": "Non EU language", "type_value": "4"},
    "en": {"label": "English (en)", "order": "english (en)", "type": "EU official language", "type_value": "16"},
    "eo": {"label": "esperanto (eo)", "order": "esperanto (eo)", "type": "Non EU language", "type_value": "4"},
    "et": {"label": "eesti keel (et)", "order": "eesti keel (et)", "type": "EU official language", "type_value": "8"},
    "ee": {"label": "Ɛʋɛgbɛ (ee)", "order": "ewe (ee)", "type": "Non EU language", "type_value": "4"},
    "fo": {"label": "Føroyskt (fo)", "order": "faroese (fo)", "type": "Non EU language", "type_value": "4"},
    "fj": {"label": "vosa Vakaviti (fj)", "order": "vosa Vakaviti (fj)", "type": "Non EU language", "type_value": "4"},
    "fi": {"label": "suomi (fi)", "order": "suomi (fi)", "type": "EU official language", "type_value": "8"},
    "fr": {"label": "français (fr)", "order": "francais (fr)", "type": "EU official language", "type_value": "16"},
    "ff": {"label": "fulfulde (ff)", "order": "fulfulde (ff)", "type": "Non EU language", "type_value": "4"},
    "gl": {"label": "Galego (gl)", "order": "galego (gl)", "type": "Non EU language", "type_value": "4"},
    "lg": {"label": "Luganda (lg)", "order": "luganda (lg)", "type": "Non EU language", "type_value": "4"},
    "ka": {"label": "ქართული (ka)", "order": "georgian (ka)", "type": "Non EU language", "type_value": "4"},
    "de": {"label": "Deutsch (de)", "order": "deutsch (de)", "type": "EU official language", "type_value": "16"},
    "el": {"label": "ελληνικά (el)", "order": "ellinika (el)", "type": "EU official language", "type_value": "8"},
    "gn": {"label": "Avañe'ẽ (gn)", "order": "guaraní (gn)", "type": "Non EU language", "type_value": "4"},
    "gu": {"label": "ગુજરાતી (gu)", "order": "gujarati (gu)", "type": "Non EU language", "type_value": "4"},
    "ht": {
        "label": "Kreyòl ayisyen (ht)",
        "order": "kreyol ayisyen (ht)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "ha": {"label": "‫هَوُسَ ‪(ha)", "order": "hausa (ha)", "type": "Non EU language", "type_value": "4"},
    "he": {"label": "‫עברית ‪(he)", "order": "hebrew (he)", "type": "Non EU language", "type_value": "4"},
    "hH": {"label": "Otjiherero (hz)", "order": "otjiherero (hz)", "type": "Non EU language", "type_value": "4"},
    "hi": {"label": "हिन्दी (hi)", "order": "hindi (hi)", "type": "Non EU language", "type_value": "4"},
    "ho": {"label": "hiri motu (ho)", "order": "hiri motu (ho)", "type": "Non EU language", "type_value": "4"},
    "hu": {"label": "magyar (hu)", "order": "magyar (hu)", "type": "EU official language", "type_value": "8"},
    "is": {"label": "islensk (is)", "order": "islensk (is)", "type": "EU non official language", "type_value": "1"},
    "io": {"label": "ido (io)", "order": "ido (io)", "type": "Non EU language", "type_value": "4"},
    "ig": {"label": "igbo (ig)", "order": "igbo (ig)", "type": "Non EU language", "type_value": "4"},
    "id": {
        "label": "Bahasa Indonesia (id)",
        "order": "bahasa Indonesia (id)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "ia": {
        "label": "interlingua (ia)",
        "order": "interlingua (International Auxiliary Language Association) (ia)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "ie": {"label": "interlingue (ie)", "order": "interlingue (ie)", "type": "Non EU language", "type_value": "4"},
    "iu": {"label": "inuktitut (iu)", "order": "inuktitut (iu)", "type": "Non EU language", "type_value": "4"},
    "ik": {"label": "Iñupiaq (ik)", "order": "inupiaq (ik)", "type": "Non EU language", "type_value": "4"},
    "ga": {"label": "Gaeilge (ga)", "order": "gaeilge (ga)", "type": "EU official language", "type_value": "8"},
    "it": {"label": "italiano (it)", "order": "italiano (it)", "type": "EU official language", "type_value": "8"},
    "ja": {"label": "日本語 (ja)", "order": "japanese (ja)", "type": "Non EU language", "type_value": "4"},
    "jv": {"label": "basa Jawa (jv)", "order": "basa Jawa (jv)", "type": "Non EU language", "type_value": "4"},
    "kl": {"label": "kalaallisut (kl)", "order": "kalaallisut (kl)", "type": "Non EU language", "type_value": "4"},
    "kn": {"label": "ಕನ್ನಡ (kn)", "order": "kannada (kn)", "type": "Non EU language", "type_value": "4"},
    "kr": {"label": "kanuri (kr)", "order": "kanuri (kr)", "type": "Non EU language", "type_value": "4"},
    "ks": {"label": "कश्मीरी (ks)", "order": "kashmiri (ks)", "type": "Non EU language", "type_value": "4"},
    "kk": {"label": "Қазақ тілі (kk)", "order": "kazakh (kk)", "type": "Non EU language", "type_value": "4"},
    "km": {"label": "ភាសាខ្មែរ (km)", "order": "khmer (km)", "type": "Non EU language", "type_value": "4"},
    "ki": {"label": "Gĩkũyũ (ki)", "order": "gikuyu (ki)", "type": "Non EU language", "type_value": "4"},
    "rw": {"label": "Ikinyarwanda (rw)", "order": "lkinyarwanda (rw)", "type": "Non EU language", "type_value": "4"},
    "ky": {"label": "кыргыз тили (ky)", "order": "kirghiz (ky)", "type": "Non EU language", "type_value": "4"},
    "rn": {"label": "kiRundi (rn)", "order": "kirundi (rn)", "type": "Non EU language", "type_value": "4"},
    "kv": {"label": "коми кыв (kv)", "order": "komi (kv)", "type": "Non EU language", "type_value": "4"},
    "kg": {"label": "KiKongo (kg)", "order": "kikongo (kg)", "type": "Non EU language", "type_value": "4"},
    "ko": {"label": "한국어 (韓國語) (ko)", "order": "korean (ko)", "type": "Non EU language", "type_value": "4"},
    "ku": {"label": "Kurdî (ku)", "order": "kurdi (ku)", "type": "Non EU language", "type_value": "4"},
    "kj": {"label": "Kuanyama (kj)", "order": "kuanyama (kj)", "type": "Non EU language", "type_value": "4"},
    "lo": {"label": "ພາສາລາວ (lo)", "order": "lao (lo)", "type": "Non EU language", "type_value": "4"},
    "la": {"label": "latine (la)", "order": "latine (la)", "type": "Non EU language", "type_value": "4"},
    "lv": {
        "label": "latviešu valoda (lv)",
        "order": "latviesu valoda (lv)",
        "type": "EU official language",
        "type_value": "8"
    },
    "li": {"label": "Limburgs (li)", "order": "limburgs (li)", "type": "Non EU language", "type_value": "4"},
    "ln": {"label": "Lingála (ln)", "order": "lingala (ln)", "type": "Non EU language", "type_value": "4"},
    "lt": {
        "label": "lietuvių kalba (lt)",
        "order": "lietuviu kalba (lt)",
        "type": "EU official language",
        "type_value": "8"
    },
    "lu": {"label": "luba-katanga (lu)", "order": "luba-katanga (lu)", "type": "Non EU language", "type_value": "4"},
    "lb": {
        "label": "Lëtzebuergesch (lb)",
        "order": "Letzebuergesch (lb)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "mk": {
        "label": "makedonski (mk)",
        "order": "makedonski (mk)",
        "type": "EU non official language",
        "type_value": "1"
    },
    "mg": {
        "label": "Malagasy fiteny (mg)",
        "order": "malagasy fiteny (mg)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "ms": {"label": "بهاس ملاي (ms)", "order": "bahasa melayu (ms)", "type": "Non EU language", "type_value": "4"},
    "ml": {"label": "Malayalam (ml)", "order": "malayalam (ml)", "type": "Non EU language", "type_value": "4"},
    "mt": {"label": "Malti (mt)", "order": "malti (mt)", "type": "EU official language", "type_value": "8"},
    "gv": {"label": "Ghaelg (gv)", "order": "ghaelg (gv)", "type": "Non EU language", "type_value": "4"},
    "mi": {"label": "te reo Māori (mi)", "order": "te reo maori (mi)", "type": "Non EU language", "type_value": "4"},
    "mr": {"label": "मराठी (mr)", "order": "marathi (mr)", "type": "Non EU language", "type_value": "4"},
    "mh": {"label": "Kajin M̧ajeļ (mh)", "order": "kajin majel (mh)", "type": "Non EU language", "type_value": "4"},
    "mo": {"label": "Moldovenească (mo)", "order": "moldavian (mo)", "type": "Non EU language", "type_value": "4"},
    "mn": {"label": "Монгол (mn)", "order": "mongolian (mn)", "type": "Non EU language", "type_value": "4"},
    "na": {
        "label": "Ekakairũ Naoero (na)",
        "order": "ekakairu Naoero (na)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "nv": {"label": "Diné bizaad (nv)", "order": "Dine bizaad (nv)", "type": "Non EU language", "type_value": "4"},
    "ng": {"label": "Owambo (ng)", "order": "owambo (ng)", "type": "Non EU language", "type_value": "4"},
    "ne": {"label": "नेपाली (ne)", "order": "nepali (ne)", "type": "Non EU language", "type_value": "4"},
    "ZZ": {"label": "No language (zz)", "order": "zz (zz)", "type": "Non EU language", "type_value": "4"},
    "nd": {"label": "isiNdebele (nd)", "order": " isindebele (nd)", "type": "Non EU language", "type_value": "4"},
    "se": {
        "label": "Davvisámegiella (se)",
        "order": "davvisamegiella (se)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "no": {"label": "norsk (no)", "order": "norsk (no)", "type": "EU non official language", "type_value": "1"},
    "nb": {"label": "Norsk bokmål (nb)", "order": "norsk bokmal (nb)", "type": "Non EU language", "type_value": "4"},
    "nn": {"label": "Norsk nynorsk (nn)", "order": "norsk nynorsk (nn)", "type": "Non EU language", "type_value": "4"},
    "oc": {"label": "occitan (oc)", "order": "occitan (oc)", "type": "Non EU language", "type_value": "4"},
    "oj": {"label": "ojibwa (oj)", "order": "ojibwa (oj)", "type": "Non EU language", "type_value": "4"},
    "or": {"label": "Oriya (or)", "order": "oriya (or)", "type": "Non EU language", "type_value": "4"},
    "om": {"label": "Afaan Oromoo (om)", "order": "afaan_oromoo (om)", "type": "Non EU language", "type_value": "4"},
    "os": {"label": "Ирон æвзаг (os)", "order": "ossetian (os)", "type": "Non EU language", "type_value": "4"},
    "pi": {"label": "पाऴि (pi)", "order": "pali (pi)", "type": "Non EU language", "type_value": "4"},
    "pa": {"label": "ਪੰਜਾਬੀ (pa)", "order": "panjabi (pa)", "type": "Non EU language", "type_value": "4"},
    "ps": {"label": "‫پښتو ‪(ps)", "order": "pashto (ps)", "type": "Non EU language", "type_value": "4"},
    "fa": {"label": "‫فارسی ‪(fa)", "order": "persian (fa)", "type": "Non EU language", "type_value": "4"},
    "pl": {"label": "polski (pl)", "order": "polski (pl)", "type": "EU official language", "type_value": "8"},
    "pt": {"label": "português (pt)", "order": "portugues (pt)", "type": "EU official language", "type_value": "8"},
    "qu": {"label": "Kichwa (qu)", "order": "kichwa (qu)", "type": "Non EU language", "type_value": "4"},
    "rm": {
        "label": "rumantsch grischun (rm)",
        "order": "rumantsch grischun (rm)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "ro": {"label": "română (ro)", "order": "romana (ro)", "type": "EU official language", "type_value": "8"},
    "ru": {"label": "русский язык (ru)", "order": "russian (ru)", "type": "Non EU language", "type_value": "4"},
    "sm": {
        "label": "gagana fa'a Samoa (sm)",
        "order": "gagana fa a Samoa (sm)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "sg": {
        "label": "yângâ tî sängö (sg)",
        "order": "yanga ti sango (sg)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "sa": {"label": "संस्कृतम (sa)", "order": "sanskrit (sa)", "type": "Non EU language", "type_value": "4"},
    "sc": {"label": "sardu (sc)", "order": "sardu (sc)", "type": "Non EU language", "type_value": "4"},
    "gd": {"label": "Gàidhlig (gd)", "order": "gaidhlig (gd)", "type": "Non EU language", "type_value": "4"},
    "sr": {"label": "Srpski (sr)", "order": "serbian (sr)", "type": "Non EU language", "type_value": "4"},
    "sh": {
        "label": "Српскохрватски (sh)",
        "order": "serbo-croatian (sh)",
        "type": "Non EU language",
        "type_value": "4"
    },
    "sn": {"label": "chiShona (sn)", "order": "chishona (sn)", "type": "Non EU language", "type_value": "4"},
    "ii": {"label": "sichuan yi (ii)", "order": "sichuan yi (ii)", "type": "Non EU language", "type_value": "4"},
    "sd": {"label": "सिन्धी (sd)", "order": "sindhi (sd)", "type": "Non EU language", "type_value": "4"},
    "si": {"label": "සිංහල (si)", "order": "sinhalese (si)", "type": "Non EU language", "type_value": "4"},
    "sk": {"label": "slovenčina (sk)", "order": "slovencina (sk)", "type": "EU official language", "type_value": "8"},
    "sl": {"label": "slovenščina (sl)", "order": "slovenscina (sl)", "type": "EU official language", "type_value": "8"},
    "so": {"label": "Soomaaliga (so)", "order": "soomaaliga (so)", "type": "Non EU language", "type_value": "4"},
    "st": {"label": "Sesotho (st)", "order": "sesotho (st)", "type": "Non EU language", "type_value": "4"},
    "nr": {"label": "Ndébélé (nr)", "order": "ndebele (nr)", "type": "Non EU language", "type_value": "4"},
    "es": {"label": "español (es)", "order": "espanol (es)", "type": "EU official language", "type_value": "8"},
    "su": {"label": "Basa Sunda (su)", "order": "basasunda (su)", "type": "Non EU language", "type_value": "4"},
    "sw": {"label": "Kiswahili (sw)", "order": "kiswahili (sw)", "type": "Non EU language", "type_value": "4"},
    "ss": {"label": "SiSwati (ss)", "order": "siswati (ss)", "type": "Non EU language", "type_value": "4"},
    "sv": {"label": "svenska (sv)", "order": "svenska (sv)", "type": "EU official language", "type_value": "8"},
    "tl": {"label": "tagalog (tl)", "order": "tagalog (tl)", "type": "Non EU language", "type_value": "4"},
    "ty": {"label": "Reo Mā`ohi (ty)", "order": "reo Ma ohi (ty)", "type": "Non EU language", "type_value": "4"},
    "tg": {"label": "тоҷикӣ (tg)", "order": "tajik (tg)", "type": "Non EU language", "type_value": "4"},
    "ta": {"label": "தமிழ் (ta)", "order": "tamil (ta)", "type": "Non EU language", "type_value": "4"},
    "tt": {"label": "татарча (tt)", "order": "tatar (tt)", "type": "Non EU language", "type_value": "4"},
    "te": {"label": "తెలుగు (te)", "order": "telugu (te)", "type": "Non EU language", "type_value": "4"},
    "tm": {"label": "Tetun (tn)", "order": "tetum (tm)", "type": "Non EU language", "type_value": "4"},
    "th": {"label": "ไทย (th)", "order": "thai (th)", "type": "Non EU language", "type_value": "4"},
    "bo": {"label": "བོད་ཡིག (bo)", "order": "tibetan (bo)", "type": "Non EU language", "type_value": "4"},
    "ti": {"label": "tigrinya (ti)", "order": "tigrinya (ti)", "type": "Non EU language", "type_value": "4"},
    "to": {"label": "faka Tonga (to)", "order": "faka tonga (to)", "type": "Non EU language", "type_value": "4"},
    "ts": {"label": "xiTsonga (ts)", "order": "xitsonga (ts)", "type": "Non EU language", "type_value": "4"},
    "tn": {"label": "seTswana (tn)", "order": "setswana (tn)", "type": "Non EU language", "type_value": "4"},
    "tr": {"label": "Türkçe (tr)", "order": "turkce (tr)", "type": "EU non official language", "type_value": "1"},
    "tk": {"label": "Türkmen (tk)", "order": "turkmen (tk)", "type": "Non EU language", "type_value": "4"},
    "tw": {"label": "twi (tw)", "order": "twi (tw)", "type": "Non EU language", "type_value": "4"},
    "ug": {"label": "yƣurqə (ug)", "order": "uighur (ug)", "type": "Non EU language", "type_value": "4"},
    "uk": {"label": "Українська (uk)", "order": "ukrainian (uk)", "type": "Non EU language", "type_value": "4"},
    "ur": {"label": "‫اردو ‪(ur)", "order": "urdu (ur)", "type": "Non EU language", "type_value": "4"},
    "uU": {"label": "O'zbek (uz)", "order": "ozbek (uz)", "type": "Non EU language", "type_value": "4"},
    "ve": {"label": "tshiVenḓa (ve)", "order": "tshivenda (ve)", "type": "Non EU language", "type_value": "4"},
    "vi": {"label": "Tiếng Việt (vi)", "order": "tieng viet (vi)", "type": "Non EU language", "type_value": "4"},
    "vo": {"label": "volapük (vo)", "order": "volapuk (vo)", "type": "Non EU language", "type_value": "4"},
    "wa": {"label": "walon (wa)", "order": "walon (wa)", "type": "Non EU language", "type_value": "4"},
    "cy": {"label": "cymraeg (cy)", "order": "welsh (cy)", "type": "Non EU language", "type_value": "4"},
    "fy": {"label": "Frysk (fy)", "order": "frysk (fy)", "type": "Non EU language", "type_value": "4"},
    "wo": {"label": "Wollof (wo)", "order": "wollof (wo)", "type": "Non EU language", "type_value": "4"},
    "xh": {"label": "isiXhosa (xh)", "order": "isixhosa (xh)", "type": "Non EU language", "type_value": "4"},
    "yi": {"label": "‫ייִדיש ‪(yi)", "order": "yiddish (yi)", "type": "Non EU language", "type_value": "4"},
    "yo": {"label": "Yorùbá (yo)", "order": "yoruba (yo)", "type": "Non EU language", "type_value": "4"},
    "za": {"label": "Saɯ cueŋƅ (za)", "order": "zhuang (za)", "type": "Non EU language", "type_value": "4"},
    "zu": {"label": "isiZulu (zu)", "order": "isizulu (zu)", "type": "Non EU language", "type_value": "4"}
};


/**
 *
 *
 //reduce
 var reduced = languages.reduce(function(map, current) {
    var value= {};
    value.label = current.title;
    value.order = current.subject;
    value.type = current.type;
    value.type_value = current.type_value;

    map[current.language_code.substr(0,2)] = value;
    return map;
},{});

 var jsonRes = JSON.stringify(reduced);
*/